// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_exnex_gibbs
Rcpp::List cpp_exnex_gibbs(const arma::vec& time, const arma::vec& event, const arma::vec& group, const arma::mat& X, Rcpp::List priors, const int& iter, const int& warmup, const int& chains);
RcppExport SEXP _exnexSurv_cpp_exnex_gibbs(SEXP timeSEXP, SEXP eventSEXP, SEXP groupSEXP, SEXP XSEXP, SEXP priorsSEXP, SEXP iterSEXP, SEXP warmupSEXP, SEXP chainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< const int& >::type chains(chainsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_exnex_gibbs(time, event, group, X, priors, iter, warmup, chains));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exnexSurv_cpp_exnex_gibbs", (DL_FUNC) &_exnexSurv_cpp_exnex_gibbs, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_exnexSurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
