# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main Gibbs Sampler for EXNEX Survival Models
#'
#' Implements Gibbs sampling for Bayesian EXNEX right-censored
#' log-normal survival models with optional covariates.
#'
#' @param time Vector of observed follow-up times (n-vector, all > 0)
#' @param event Vector of event indicators (n-vector, 0 or 1)
#' @param group Vector of group assignments (n-vector, integers 1 to K)
#' @param X Matrix of covariates (n x P). Can be empty (n x 0) if no covariates.
#' @param priors Optional named list of prior hyperparameters. Supported
#'   fields: \code{a_sigma}, \code{b_sigma}, \code{a_tau}, \code{b_tau}
#'   (inverse-Gamma shape and scale), \code{p_mix} (EXNEX mixture weight),
#'   \code{m_mu}, \code{v_mu} (exchangeable mean prior), \code{m_nex},
#'   \code{v_nex} (nonexchangeable component), \code{v_beta} (variance of the
#'   regression-coefficient prior). \code{p_mix}, \code{m_nex}, and
#'   \code{v_nex} each accept either a scalar, replicated across baskets, or a
#'   numeric vector of length K with one value per basket, matching the
#'   basket-specific notation \eqn{p_{\mathrm{exch},j}}, \eqn{m_{0j}},
#'   \eqn{v_{0j}} of the model. Absent fields keep the defaults; unknown
#'   fields are ignored.
#' @param pooling Pooling mode: one of \code{"exnex"} (EXNEX hierarchy with
#'   mixture indicators \eqn{Z_j}, exchangeable center \eqn{\mu} and
#'   between-basket variance \eqn{\tau^2}), \code{"complete"} (a single shared
#'   basket effect with prior \eqn{\mathcal N(m_{\mu}, v_{\mu})}; the
#'   EXNEX-specific priors are ignored) or \code{"none"} (independent basket
#'   effects with priors \eqn{\mathcal N(m_{0j}, v_{0j})}; the EXNEX-specific
#'   priors are ignored).
#' @param verbose If \code{TRUE}, report chain progress every 10\% of the
#'   iterations on the standard output (or through \code{progress_hook});
#'   silence with \code{verbose = FALSE}. Default \code{TRUE}.
#' @param iter Total number of MCMC iterations
#' @param warmup Number of iterations to discard
#' @param thin Keep every \code{thin}-th post-warmup draw (thinning
#'   interval); must be a positive integer
#' @param chains Number of independent chains to run
#' @param chain_label Optional label (e.g. the chain number) shown in the
#'   progress lines; empty string omits it.
#' @param progress_hook Optional R function called with one argument
#'   (the progress line) at every 10\% milestone instead of printing to the
#'   standard output; used by the parallel runner to relay progress to the
#'   master session.
#'
#' @return List containing posterior draws, priors, metadata, and diagnostics
#' @keywords internal
cpp_exnex_gibbs <- function(time, event, group, X, priors, pooling, verbose, iter, warmup, thin, chains, chain_label, progress_hook = NULL) {
    .Call(`_exnexSurv_cpp_exnex_gibbs`, time, event, group, X, priors, pooling, verbose, iter, warmup, thin, chains, chain_label, progress_hook)
}

